#!/usr/bin/env lua

local hi = vim.api.nvim_set_hl

hi(0, "Visual", { ctermbg = "lightgray", ctermfg = "black", bg = "lightgray", fg = "black" })
hi(0, "Conceal", { ctermbg = "none", ctermfg = "none", bg = "none", fg = "none" })
-- hl(0, 'MatchParen', { ctermbg = 'none', ctermfg = 'green', bg = 'none', fg = 'lightgreen', bold = true })
hi(0, "NonText", { fg = "#1A8FFF", ctermfg = 12 })
hi(0, "Normal", { bg = "none", fg = 14738154 })
hi(0, "Pmenu", { ctermbg = 236, ctermfg = "none", bg = "#222222", fg = "none" })
hi(0, "PmenuSel", { ctermbg = 24, ctermfg = "none", bg = "#005F87", fg = "none" })
hi(0, "PmenuKind", { link = "Pmenu" })
hi(0, "PmenuKindSel", { link = "PmenuSel" })
hi(0, "PmenuMatch", { ctermfg = "yellow", fg = "#ffc978" })
hi(0, "PmenuMatchSel", { link = "PmenuMatch" })
hi(0, "Folded", { link = "Comment" })
-- hl(0, 'SpellBad', { undercurl = true, ctermbg = 'none', ctermfg = 9 })
-- hl(0, 'SpellCap', { undercurl = true, ctermbg = 'none', ctermfg = 12 })
-- hl(0, 'SpellLocal', { undercurl = true, ctermbg = 'none', ctermfg = 14 })
-- hl(0, 'SpellRare', { undercurl = true, ctermbg = 'none', ctermfg = 13 })
hi(0, "SignColumn", { ctermbg = "none", bg = "none" })
hi(0, "DiffAdd", { ctermfg = "green", fg = "green" })
hi(0, "DiffChange", { ctermfg = "yellow", fg = "yellow" })
hi(0, "DiffDelete", { ctermfg = "red", fg = "red" })
hi(0, "StatusLine", { underline = true, bold = true })
hi(0, "StatusLineNC", { underline = true })
-- hl(0, 'CursorLine', { underline = true })
hi(0, "TermCursor", { link = "Cursor" })
