#!/bin/sh

# Example for $XDG_CONFIG_HOME/nsxiv/exec/key-handler
# Called by nsxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon: all marked images, if in thumbnail mode and at least one
# image has been marked, otherwise the current image. nsxiv(1) will block until
# the handler terminates. It then checks which images have been modified and
# reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.
# If KEY has an uppercase equivalent, S-KEY is resolved into it. For instance,
# K replaces S-k and Scedilla replaces S-scedilla, but S-Delete is sent as-is.

# By default nsxiv(1) will send one image per-line to stdin, however when using
# -0 the image list will be NULL separated and the environment variable
# "$NSXIV_USING_NULL" will be set to 1.

[ "$NSXIV_USING_NULL" = 1 ] && DELIM='\0' || DELIM='\n'

rotate() {
	tr "$DELIM" '\0' | xargs -0 realpath -z | sort -z -u | xargs -0 -I {} sh -c '
		degree="$1"
		case "$(file -b -i "{}")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "{}" "{}" ;;
		*)           mogrify  -rotate "$degree" "{}" ;;
		esac
	' -- "$1"
}

case "$1" in
# copy filepath
"C-x")      while read -r file; do realpath "$file" | xclip -selection clipboard ; done ;;
# copy image
"C-c")      while read -r file; do xclip -selection clipboard -target image/png "$file"; done ;;
"C-comma")  rotate 270 ;;
"C-period") rotate  90 ;;
"C-slash")  rotate 180 ;;
esac

